#!/usr/bin/env python3
"""Turn results/docx-<g>.json and results/hwpx.json into results/RESULTS.md."""
import collections
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")


def yn(v):
    return "–" if v is None else ("yes" if v else "**no**")


def route_a(g):
    r = json.load(open(os.path.join(RES, "docx-%s.json" % g)))["route_a"]
    ok = [x for x in r if x["compare"].get("ok") and x["compare"]["revisions"]["count"]]
    empty = [x for x in r if x["compare"].get("ok") and not x["compare"]["revisions"]["count"]]
    refused = collections.Counter()
    for x in r:
        if not x["compare"].get("ok"):
            e = re.sub(r"\[\d+\]|\d{3,}", "…", x["compare"]["error"])
            e = e.split(":")[0] if "does not reproduce" in e or "duplicate drawing" in e else e
            refused[e[:110]] += 1
    c = collections.Counter()
    for x in ok:
        rd, t, lo = x.get("rdocx", {}), x.get("text", {}), x.get("lo", {})
        c["wf"] += not x["wf_errors"]
        c["ws"] += x["ws_unpreserved"] == 0
        c["reopen"] += bool(rd.get("ok")) and rd.get("revisions", {}).get("count", 0) > 0
        c["resave"] += rd.get("resave", {}).get("revisions", {}).get("count") == rd.get("revisions", {}).get("count")
        c["kept"] += (lambda k: k and k.split("/")[0] == k.split("/")[1])(rd.get("revision_xml_kept_on_save"))
        c["acc"] += bool(t.get("rdocx_accept_eq_edited"))
        c["rej"] += bool(t.get("rdocx_reject_eq_base"))
        c["pdf"] += bool(rd.get("tracked_pdf", {}).get("ok"))
        c["lo_open"] += bool(lo.get("ok"))
        c["lo_red"] += lo.get("redlines", {}).get("count", 0) > 0
        c["lo_acc"] += bool(lo.get("accept_matches_edited") or lo.get("accept_matches_ignoring_field_digits"))
        c["lo_rej"] += bool(lo.get("reject_matches_base") or lo.get("reject_matches_ignoring_field_digits"))
    return r, ok, refused, c, empty


def main():
    L = ["# Tracked-changes spike: generated results", "",
         "Generated by `summarize.py` from `results/*.json`. Word and Hancom were not run.", ""]
    for g in ("run", "word"):
        r, ok, refused, c, empty = route_a(g)
        n = len(ok)
        L += ["## docx route A: rdocx `compare_with_options`, granularity `%s`" % g.capitalize(), "",
              "%d direct-change exports (13 files × E1–E10 where the edit applies). compare wrote revisions for **%d**, wrote none for %d (%s), refused %d." % (
                  len(r), n, len(empty), ", ".join("%s %s" % (x["file"], x["edit"]) for x in empty) or "–", len(r) - n - len(empty)), "",
              "| Check (of the %d tracked files) | pass |" % n, "|---|---|"]
        for k, label in (("wf", "every XML part well-formed"), ("ws", "no whitespace-only/edge-space `w:t` without `xml:space=\"preserve\"`"),
                         ("reopen", "rdocx re-opens, `revisions()` lists them"), ("resave", "rdocx save + re-open keeps every revision"),
                         ("kept", "revision XML byte-identical after rdocx save"),
                         ("acc", "rdocx `accept_all` text == edited export"), ("rej", "rdocx `reject_all` text == unedited export"),
                         ("pdf", "rdocx tracked-view PDF renders"), ("lo_open", "LibreOffice opens it"),
                         ("lo_red", "LibreOffice lists ≥ 1 tracked change"), ("lo_acc", "LibreOffice Accept All text == edited (field digits masked)"),
                         ("lo_rej", "LibreOffice Reject All text == unedited (field digits masked)")):
            L.append("| %s | %d |" % (label, c[k]))
        L += ["", "Refusals:", "", "| count | rdocx error |", "|---|---|"]
        for e, k in refused.most_common():
            L.append("| %d | `%s` |" % (k, e.replace("|", "\\|")))
        L += ["", "<details><summary>Per file</summary>", "",
              "| file | edit | revisions | wf | ws ok | rdocx acc/rej | LO redlines | LO acc/rej |", "|---|---|---|---|---|---|---|---|"]
        for x in ok:
            rd, t, lo = x.get("rdocx", {}), x.get("text", {}), x.get("lo", {})
            L.append("| %s | %s | %s | %s | %s | %s/%s | %s | %s/%s |" % (
                x["file"], x["edit"], " ".join("%s %d" % kv for kv in x["compare"]["revisions"]["by_kind"].items()),
                yn(not x["wf_errors"]), yn(x["ws_unpreserved"] == 0), yn(t.get("rdocx_accept_eq_edited")), yn(t.get("rdocx_reject_eq_base")),
                " ".join("%s %d" % kv for kv in lo.get("redlines", {}).get("by_type", {}).items()) or ("fails to open" if not lo.get("ok") else "0"),
                yn(lo.get("accept_matches_edited") or lo.get("accept_matches_ignoring_field_digits")),
                yn(lo.get("reject_matches_base") or lo.get("reject_matches_ignoring_field_digits"))))
        L += ["", "</details>", ""]
    b = json.load(open(os.path.join(RES, "docx-run.json")))["route_b"]
    L += ["## docx route B: revision XML written directly (`inject.py`), checked with rdocx and LibreOffice", "",
          "| file | edits | wf | rdocx revisions | save keeps XML | rdocx accept/reject | LO redlines | LO accept/reject |", "|---|---|---|---|---|---|---|---|"]
    for x in b:
        rd, t, lo = x.get("rdocx", {}), x.get("text", {}), x.get("lo", {})
        rej = rd.get("reject_all", {})
        L.append("| %s | %s | %s | %s | %s | %s/%s | %s | %s/%s |" % (
            x["file"], " ".join(e["edit"] for e in x["edits"] if e["what"] != "n/a"), yn(not x["wf_errors"]),
            " ".join("%s %d" % kv for kv in rd.get("revisions", {}).get("by_kind", {}).items()),
            rd.get("revision_xml_kept_on_save"), yn(t.get("rdocx_accept_eq_edited")),
            yn(t.get("rdocx_reject_eq_base")) if rej.get("ok") else "`%s`" % rej.get("error"),
            " ".join("%s %d" % kv for kv in lo.get("redlines", {}).get("by_type", {}).items()),
            yn(lo.get("accept_matches_edited") or lo.get("accept_matches_ignoring_field_digits")),
            yn(lo.get("reject_matches_base") or lo.get("reject_matches_ignoring_field_digits"))))
    L += ["", "Route B counts include the file's own pre-existing revisions (korean-report, tdf154481)."]
    hp = os.path.join(RES, "hwpx.json")
    if os.path.exists(hp):
        h = json.load(open(hp))
        L += ["", "## hwpx: OWPML track-change XML written directly (`hwpx_spike.py`), checked with rhwp", "",
              "| file | check | result |", "|---|---|---|"]
        for row in h["rows"]:
            for k, v in row["checks"].items():
                L.append("| %s | %s | %s |" % (row["file"], k, str(v).replace("|", "\\|").replace("\n", " ")[:300]))
    open(os.path.join(RES, "RESULTS.md"), "w").write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
