#!/bin/sh
# Re-downloads the twelve third-party corpus files from their upstream repositories at
# pinned commits and checks them against the committed copies' SHA-256.
# (The files are committed too; this script documents provenance and lets anyone verify it.)
# korean-report.docx is not fetched: it is generated by make_korean.sh.
set -e
cd "$(dirname "$0")"
POI=https://raw.githubusercontent.com/apache/poi/942d95d85b15d0dfdb3bc9ba1b4f273f277757c8/test-data/document
TIKA=https://raw.githubusercontent.com/apache/tika/df85810303bdd51e4a7f5accbcfb0d659b922631/tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/resources/test-documents
D4J=https://raw.githubusercontent.com/plutext/docx4j/0e8e7633ef46012e0d3603339728b83ed21d5045
LO=https://raw.githubusercontent.com/LibreOffice/core/ccbc8791e125f7d508931bcdf33134b44d393d39/sw/qa/extras/ooxmlexport/data
fetch() { # name url sha256
  curl -fsSL -o "$1.tmp" "$2"
  echo "$3  $1.tmp" | sha256sum -c --quiet - && mv "$1.tmp" "$1" && echo "ok  $1"
}
fetch Bug54849.docx            "$POI/Bug54849.docx"            f54182713ea5ce5d77b9593d3d9d24e645460043cec0b40ef59c932385f084d3
fetch WordWithAttachments.docx "$POI/WordWithAttachments.docx" 90352263823e6d3d39a4ec88212134b74bcb0f86b603bc3b51d712a3ec3df9f2
fetch delins.docx              "$POI/delins.docx"              7ecad102602586be7f1371f117fc567ea47f3ed0ca703b353e003002f1ff8d3f
fetch form_footnotes.docx      "$POI/form_footnotes.docx"      a890294bfbdc63f6d03eab61efc1e98cb51d59f0920541150dd7082f9bdf31f1
fetch testWORD_2006ml.docx     "$TIKA/testWORD_2006ml.docx"    a27f2b9244f5147cce25a05d4cddb1eec9c72259a41d52a7bf5eb3806b28207c
fetch testWORD_various.docx    "$TIKA/testWORD_various.docx"   f7761e3893d795ed09f12f89a16d3265c3919da549adf00127b0f7094bccd0ee
fetch loadAndSave.docx         "$D4J/docx4j-core-tests/src/test/resources/loadAndSave.docx" 122f53311702e32affbc0ec99ced129990e6728a9b4b6df30f5684f73a20247f
fetch sample-docx.docx         "$D4J/docx4j-samples-docx4j/sample-docs/sample-docx.docx"    f527fe32f4bf9e152d86a8e7f1971033e7404929c624e3bdc26853c6a0cfa25e
fetch docx4j-tables.docx       "$D4J/docx4j-samples-docx4j/sample-docs/tables.docx"         50ea2fd62761aedc66e307c30ca1191a4e6baf8fa9d8d849ba1d9c20eb5921f4
fetch fdo76098.docx            "$LO/fdo76098.docx"             72e7239635dee3b7790392ce9490218db3868e7a6519ecb7db1fa72c9e376b48
fetch tdf124637_sectionMargin.docx "$LO/tdf124637_sectionMargin.docx" 59877f0b300ca9a34e925ce1b05e2a33877ff121f19efe31b12bc472beb02e50
fetch tdf154481.docx           "$LO/tdf154481.docx"            2af13d3cd96caefbf45b149bd87cfb44e55a6a548eb3b65608e1387d54be605b
